# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1366, 768)
        Form.setMinimumSize(QtCore.QSize(1366, 768))
        Form.setMaximumSize(QtCore.QSize(1920, 1080))
        Form.setStyleSheet("background-color: rgb(46, 52, 54)")
        Form.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_7 = QtWidgets.QFrame(Form)
        self.frame_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setLineWidth(10)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(50, 50, 50, 100)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMouseTracking(False)
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.screen = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screen.sizePolicy().hasHeightForWidth())
        self.screen.setSizePolicy(sizePolicy)
        self.screen.setMinimumSize(QtCore.QSize(720, 480))
        self.screen.setMaximumSize(QtCore.QSize(720, 480))
        self.screen.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.screen.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border-color: rgb(255 ,255,255);\n"
"font: 75 15pt \"Ubuntu Condensed\";\n"
"border-width : 1.5px;\n"
"border-style:inset;\n"
"border-radius: 8px;\n"
"padding: 0 5px;\n"
"color: rgb(255, 255, 255);")
        self.screen.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.screen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.screen.setScaledContents(False)
        self.screen.setAlignment(QtCore.Qt.AlignCenter)
        self.screen.setObjectName("screen")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.screen)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.run_button = QtWidgets.QPushButton(self.frame_3)
        self.run_button.setMinimumSize(QtCore.QSize(50, 50))
        self.run_button.setMaximumSize(QtCore.QSize(50, 50))
        self.run_button.setStyleSheet("QPushButton{\n"
"    \n"
"border-color: rgb(255 ,255,255);\n"
"font: 75 15pt \"Ubuntu Condensed\";\n"
"background-color: rgb(136, 138, 133);\n"
"border-width : 1.5px;\n"
"border-style:inset;\n"
"border-radius: 8px;\n"
"padding: 0 5px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(32, 74, 135);\n"
"\n"
"}")
        self.run_button.setText("")
        self.run_button.setIconSize(QtCore.QSize(50, 50))
        self.run_button.setObjectName("run_button")
        self.horizontalLayout.addWidget(self.run_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.stop_button = QtWidgets.QPushButton(self.frame_3)
        self.stop_button.setMinimumSize(QtCore.QSize(50, 50))
        self.stop_button.setMaximumSize(QtCore.QSize(50, 50))
        self.stop_button.setStyleSheet("QPushButton{\n"
"    \n"
"border-color: rgb(255 ,255,255);\n"
"font: 75 15pt \"Ubuntu Condensed\";\n"
"background-color: rgb(136, 138, 133);\n"
"border-width : 1.5px;\n"
"border-style:inset;\n"
"border-radius: 8px;\n"
"padding: 0 5px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(32, 74, 135);\n"
"\n"
"}")
        self.stop_button.setText("")
        self.stop_button.setIconSize(QtCore.QSize(50, 50))
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.stop_button, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_6 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setContentsMargins(50, 50, 50, 50)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_5)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setSpacing(0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.sub_screen = QtWidgets.QLabel(self.frame_5)
        self.sub_screen.setMinimumSize(QtCore.QSize(200, 200))
        self.sub_screen.setMaximumSize(QtCore.QSize(200, 200))
        self.sub_screen.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border-color: rgb(255 ,255,255);\n"
"font: 75 15pt \"Ubuntu Condensed\";\n"
"border-width : 1.5px;\n"
"border-style:inset;\n"
"border-radius: 8px;\n"
"padding: 0 5px;\n"
"color: rgb(255, 255, 255);")
        self.sub_screen.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sub_screen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sub_screen.setAlignment(QtCore.Qt.AlignCenter)
        self.sub_screen.setWordWrap(False)
        self.sub_screen.setObjectName("sub_screen")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sub_screen)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_4.setContentsMargins(0, 0, 0, 100)
        self.formLayout_4.setHorizontalSpacing(0)
        self.formLayout_4.setVerticalSpacing(10)
        self.formLayout_4.setObjectName("formLayout_4")
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.formLayout_6 = QtWidgets.QFormLayout(self.frame_10)
        self.formLayout_6.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_6.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setSpacing(0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        self.label_6.setMinimumSize(QtCore.QSize(130, 30))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("font: 75 15pt \"Ubuntu Condensed\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_6)
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.formLayout_5 = QtWidgets.QFormLayout(self.frame_9)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setSpacing(10)
        self.formLayout_5.setObjectName("formLayout_5")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_7.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_7.setSpacing(10)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frame_9)
        self.label_2.setMinimumSize(QtCore.QSize(90, 30))
        self.label_2.setMaximumSize(QtCore.QSize(90, 30))
        self.label_2.setWhatsThis("")
        self.label_2.setStyleSheet("font: 75 15pt \"Ubuntu Condensed\";\n"
"border-style:inset;")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.name_screen = QtWidgets.QLabel(self.frame_9)
        self.name_screen.setMinimumSize(QtCore.QSize(210, 30))
        self.name_screen.setMaximumSize(QtCore.QSize(210, 30))
        self.name_screen.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(136, 138, 133);\n"
"border-width : 1.5px;\n"
"border-style:inset;\n"
"border-radius: 8px;\n"
"font: 75 15pt \"Ubuntu Condensed\";\n"
"padding: 0 5px;\n"
"color: rgb(255, 255, 255);")
        self.name_screen.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.name_screen.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.name_screen.setTextFormat(QtCore.Qt.AutoText)
        self.name_screen.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_screen.setObjectName("name_screen")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_screen)
        self.label_3 = QtWidgets.QLabel(self.frame_9)
        self.label_3.setMinimumSize(QtCore.QSize(90, 30))
        self.label_3.setMaximumSize(QtCore.QSize(90, 30))
        self.label_3.setWhatsThis("")
        self.label_3.setStyleSheet("font: 75 15pt \"Ubuntu Condensed\";\n"
"border-style:inset;")
        self.label_3.setObjectName("label_3")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.position_screen = QtWidgets.QLabel(self.frame_9)
        self.position_screen.setMinimumSize(QtCore.QSize(210, 30))
        self.position_screen.setMaximumSize(QtCore.QSize(210, 30))
        self.position_screen.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(136, 138, 133);\n"
"border-width : 1.5px;\n"
"border-style:inset;\n"
"border-radius: 8px;\n"
"font: 75 15pt \"Ubuntu Condensed\";\n"
"padding: 0 5px;\n"
"color: rgb(255, 255, 255);")
        self.position_screen.setObjectName("position_screen")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.position_screen)
        self.label_4 = QtWidgets.QLabel(self.frame_9)
        self.label_4.setMinimumSize(QtCore.QSize(90, 30))
        self.label_4.setMaximumSize(QtCore.QSize(90, 30))
        self.label_4.setStyleSheet("font: 75 15pt \"Ubuntu Condensed\";\n"
"border-style:inset;")
        self.label_4.setObjectName("label_4")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.office_screen = QtWidgets.QLabel(self.frame_9)
        self.office_screen.setMinimumSize(QtCore.QSize(210, 30))
        self.office_screen.setMaximumSize(QtCore.QSize(210, 30))
        self.office_screen.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(136, 138, 133);\n"
"border-width : 1.5px;\n"
"border-style:inset;\n"
"border-radius: 8px;\n"
"font: 75 15pt \"Ubuntu Condensed\";\n"
"padding: 0 5px;\n"
"color: rgb(255, 255, 255);")
        self.office_screen.setObjectName("office_screen")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.office_screen)
        self.label = QtWidgets.QLabel(self.frame_9)
        self.label.setMinimumSize(QtCore.QSize(90, 30))
        self.label.setMaximumSize(QtCore.QSize(90, 30))
        self.label.setStyleSheet("font: 75 15pt \"Ubuntu Condensed\";\n"
"border-style:inset;")
        self.label.setObjectName("label")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.time_screen = QtWidgets.QLabel(self.frame_9)
        self.time_screen.setMinimumSize(QtCore.QSize(210, 30))
        self.time_screen.setMaximumSize(QtCore.QSize(210, 30))
        self.time_screen.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(136, 138, 133);\n"
"border-width : 1.5px;\n"
"border-style:inset;\n"
"border-radius: 8px;\n"
"font: 75 15pt \"Ubuntu Condensed\";\n"
"padding: 0 5px;\n"
"color: rgb(255, 255, 255);")
        self.time_screen.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.time_screen.setObjectName("time_screen")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.time_screen)
        self.formLayout_5.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.formLayout_7)
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.gridLayout_2.addWidget(self.frame_7, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.screen.setText(_translate("Form", "Screen"))
        self.sub_screen.setText(_translate("Form", "Sub Screen"))
        self.label_6.setText(_translate("Form", "INFORMATION"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Name</span></p></body></html>"))
        self.name_screen.setText(_translate("Form", "None"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Position</span></p></body></html>"))
        self.position_screen.setText(_translate("Form", "None"))
        self.label_4.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Office</span></p></body></html>"))
        self.office_screen.setText(_translate("Form", "None"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Time</span></p></body></html>"))
        self.time_screen.setText(_translate("Form", "None"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
