# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tab_2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1366, 780)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 60, 271, 61))
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(100, 150, 281, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.position = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.position.setObjectName("position")
        self.gridLayout.addWidget(self.position, 1, 1, 1, 1)
        self.office = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.office.setObjectName("office")
        self.gridLayout.addWidget(self.office, 2, 1, 1, 1)
        self.screen = QtWidgets.QLabel(Form)
        self.screen.setGeometry(QtCore.QRect(490, 120, 720, 480))
        self.screen.setStyleSheet("background-color: rgb(156, 155, 155);")
        self.screen.setAlignment(QtCore.Qt.AlignCenter)
        self.screen.setObjectName("screen")
        self.cap_button = QtWidgets.QPushButton(Form)
        self.cap_button.setGeometry(QtCore.QRect(170, 320, 131, 81))
        self.cap_button.setObjectName("cap_button")
        self.create_person = QtWidgets.QPushButton(Form)
        self.create_person.setGeometry(QtCore.QRect(170, 440, 131, 101))
        self.create_person.setObjectName("create_person")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(800, 70, 91, 41))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600; color:#204a87;\">New employee</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; font-style:italic; text-decoration: underline;\">Positon</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; font-style:italic; text-decoration: underline;\">Office</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; font-style:italic; text-decoration: underline;\">Name</span></p></body></html>"))
        self.screen.setText(_translate("Form", "Screen"))
        self.cap_button.setText(_translate("Form", "Chụp"))
        self.create_person.setText(_translate("Form", "Hoàn tất"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#204a87;\">Camera</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
